"""initial_schema

Revision ID: 660be44ce009
Revises: 
Create Date: 2026-04-09 06:09:32.542043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '660be44ce009'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_providers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('env_key_name', sa.String(), nullable=True),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_name')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('llm_models',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['llm_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('github_url', sa.String(), nullable=False),
    sa.Column('pat', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('clone_path', sa.String(), nullable=True),
    sa.Column('sonar_project_key', sa.String(), nullable=True),
    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('agent_role', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('system_prompt_override', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['llm_models.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['llm_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_name')
    )
    op.create_table('quality_gates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repo_id', sa.String(), nullable=False),
    sa.Column('min_severity', sa.String(), nullable=False),
    sa.Column('max_issues_per_run', sa.Integer(), nullable=False),
    sa.Column('auto_fix_enabled', sa.Boolean(), nullable=False),
    sa.Column('file_exclusions', sa.Text(), nullable=False),
    sa.Column('rule_exclusions', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id')
    )
    op.create_table('scan_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repo_id', sa.String(), nullable=False),
    sa.Column('triggered_by', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('scan_type', sa.String(), nullable=False),
    sa.Column('parent_scan_id', sa.String(), nullable=True),
    sa.Column('sonar_task_id', sa.String(), nullable=True),
    sa.Column('total_issues', sa.Integer(), nullable=False),
    sa.Column('issues_by_severity', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_scan_id'], ['scan_runs.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('scan_run_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('provider_used', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_logs_agent_name'), 'agent_logs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_logs_scan_run_id'), 'agent_logs', ['scan_run_id'], unique=False)
    op.create_table('agent_memory',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('entity_key', sa.String(), nullable=False),
    sa.Column('memory_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('scan_run_id', sa.String(), nullable=True),
    sa.Column('recall_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_memory_agent_name'), 'agent_memory', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_memory_entity_key'), 'agent_memory', ['entity_key'], unique=False)
    op.create_table('delta_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repo_id', sa.String(), nullable=False),
    sa.Column('before_scan_id', sa.String(), nullable=False),
    sa.Column('after_scan_id', sa.String(), nullable=False),
    sa.Column('total_before', sa.Integer(), nullable=True),
    sa.Column('total_after', sa.Integer(), nullable=True),
    sa.Column('fixed_count', sa.Integer(), nullable=True),
    sa.Column('new_count', sa.Integer(), nullable=True),
    sa.Column('improvement_pct', sa.Float(), nullable=True),
    sa.Column('severity_breakdown', sa.Text(), nullable=True),
    sa.Column('rule_breakdown', sa.Text(), nullable=True),
    sa.Column('file_breakdown', sa.Text(), nullable=True),
    sa.Column('summary_narrative', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['after_scan_id'], ['scan_runs.id'], ),
    sa.ForeignKeyConstraint(['before_scan_id'], ['scan_runs.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delta_reports_repo_id'), 'delta_reports', ['repo_id'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_run_id', sa.String(), nullable=False),
    sa.Column('sonar_key', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('rule_key', sa.String(), nullable=False),
    sa.Column('rule_name', sa.String(), nullable=True),
    sa.Column('component', sa.String(), nullable=False),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('effort', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('selected_for_fix', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_run_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_scan_run_id'), 'pipeline_runs', ['scan_run_id'], unique=False)
    op.create_table('fixes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('issue_id', sa.String(), nullable=False),
    sa.Column('scan_run_id', sa.String(), nullable=False),
    sa.Column('agent_run_id', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('original_code', sa.Text(), nullable=False),
    sa.Column('fixed_code', sa.Text(), nullable=False),
    sa.Column('diff_patch', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('reviewer_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fix_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('fix_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('edited_code', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fix_id'], ['fixes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fix_reviews')
    op.drop_table('fixes')
    op.drop_index(op.f('ix_pipeline_runs_scan_run_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_table('issues')
    op.drop_index(op.f('ix_delta_reports_repo_id'), table_name='delta_reports')
    op.drop_table('delta_reports')
    op.drop_index(op.f('ix_agent_memory_entity_key'), table_name='agent_memory')
    op.drop_index(op.f('ix_agent_memory_agent_name'), table_name='agent_memory')
    op.drop_table('agent_memory')
    op.drop_index(op.f('ix_agent_logs_scan_run_id'), table_name='agent_logs')
    op.drop_index(op.f('ix_agent_logs_agent_name'), table_name='agent_logs')
    op.drop_table('agent_logs')
    op.drop_table('scan_runs')
    op.drop_table('quality_gates')
    op.drop_table('agent_configs')
    op.drop_table('repos')
    op.drop_table('llm_models')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('llm_providers')
    # ### end Alembic commands ###
